name: github-runners

services:
  runner:
    build: .
    container_name: ${RUNNER_NAME:-sopo-budget-runner}
    restart: unless-stopped
    env_file: .env
    volumes:
      - runner-work:/runner/_work
    environment:
      - RUNNER_ALLOW_RUNASROOT=1

volumes:
  runner-work:
